def test_order(browser):
    start_page = StartPage(browser)
    form_order = FormOrder(browser)
    form_order_rent = OrderRent(browser)
    start_page.go_to_site()
    start_page.click_order_button()
    form_order.enter_name("Имя")
    form_order.enter_sername("Фамилия")
    form_order.enter_adress("Адрес")
    form_order.enter_metro("Метро")
    form_order.enter_phone("89113456789")
    form_order.click_next_button()
    form_order_rent.enter_data("21.03.2023")
    form_order_rent.enter_period()
    form_order_rent.enter_color()
    form_order_rent.enter_comment("")
    form_order_rent.click_order_button()
    form_order_rent.click_order_ok_button()
    order_text = form_order_rent.check_text()
    assert "Номер заказа" in order_text
